### ISSUE TITLE
Some data in tables not found after header update

### ISSUE THREAD

**Issue by lukehsiao** [xiao-cheng/table-extraction#6]
When I run ```deepdive initdb``` now, which runs 112823.pdf through table-extraction, it seems like I do not get all of the table information that I used to get. For example, on the first page of the PDF, it seems like I no longer get the cells in the table under Symbol, Value, or Unit. Instead, I just get the things in the first column under Rating.

That said, I seem to get more than the first column on the second page:

```
lh@lh:~/repos/HardwareDeepDive$ deepdive sql "select * from table_dump where mention_text='Symbol'"
   doc_id   | page_num | table_id |  relation  | relation_id | mention_text | mention_id
------------+----------+----------+------------+-------------+--------------+------------
 112823.pdf |        1 |        0 | row        |           0 | Symbol       |          1
 112823.pdf |        1 |        0 | left_col   |          10 | Symbol       |          1
 112823.pdf |        1 |        0 | center_col |          15 | Symbol       |          1
 112823.pdf |        1 |        0 | right_col  |          17 | Symbol       |          1
```

I would've expected this SQL query to also give me Symbol on page_num=0 for the Maximum Ratings table and the Thermal Characteristics table.

**Comment by lukehsiao** [comment]
Holly and I just did a test of a [newer version of this PDF](http://www.onsemi.com/pub_link/Collateral/BC546-D.PDF) and the table-extractor seems to work fine.

So, it may be an issue with the PDF itself? However, before the header updates all of the information was extracted correctly on 112823.pdf itself, so I'm not sure if it is just caused by the updated code.

**Comment by xiao-cheng** [comment]
Yes I did notice this.. I need to redo a lot of the table detection code since it is not robust enough in a lot of pdfs. OS X seems to rewrite every pdf after I opened it for some reason, which created some of the problems here

**Comment by xiao-cheng** [comment]
Fixed
